// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HtmlForJavascript
{
    internal sealed partial class Vsix
    {
        public const string Id = "7a31876a-307d-42f3-8394-49482314ae7a";
        public const string Name = "HTML for JavaScript";
        public const string Description = @"Colorizes HTML strings inside JavaScript and TypeScript. Works great for embedding HTML inside your script files.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "html. javascript, typescript, strings";
    }
}
